name: User Service CI Pipeline

on:
  push:
    branches:
      - master
    paths:
      - 'project/userservice/**'

jobs:
  build-and-test:
    name: Build, Test, and Analyze
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven' #cashing maven dependencies for faster builds

      - name: Build, Test, and Analyze with Maven
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: >
          mvn -f project/userservice/pom.xml clean verify sonar:sonar \
          -Dsonar.projectKey=VladKulikk_InnowiseInternship \
          -Dsonar.organization=vladkulikk \
          -Dsonar.host.url=https://sonarcloud.io
          

  build-and-push-docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./project/userservice
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/userservice:latest